"""AuditRunner: orchestrates the full audit lifecycle inside the Fargate task.

Directory layout inside the ECS task:
    /tmp/audit/{job_id}/                      ← job_dir   (BULWARK_ROOT, bulwark.toml here)
    /tmp/audit/{job_id}/target/               ← audit_dir (AUDIT_DIR, cloned repo)
    /tmp/audit/{job_id}/target/audit-workspace/  ← bulwark workspace (intermediate files)
    /tmp/audit/{job_id}/target/audit-workspace/final-report.json  ← uploaded to S3 report/
"""
from __future__ import annotations

import os
import subprocess
import tempfile
import textwrap
from pathlib import Path

import boto3
import structlog

from .bulwark_log_parser import BulwarkLogParser
from .config import JobEnv
from .dynamodb_writer import DynamoWriter
from .s3_uploader import S3Uploader

log = structlog.get_logger()

JOB_ROOT = Path("/tmp/audit")

# Must match bulwark's default workspace.path config value
BULWARK_WORKSPACE_REL = "audit-workspace"

# Exit codes — see entrypoint.py module docstring
EXIT_SUCCESS = 0
EXIT_JOB_COMPILE_ERROR = 1
EXIT_JOB_UNREACHABLE_REPO = 2
EXIT_TRANSIENT_INFRA = 11
EXIT_TERMINAL_INFRA = 20


class AuditRunner:
    def __init__(self, env: JobEnv) -> None:
        self.env = env
        # job_dir: holds bulwark.toml; passed as BULWARK_ROOT to bulwark
        self.job_dir = JOB_ROOT / env.job_id
        # target_dir: the cloned repo; passed as AUDIT_DIR to bulwark
        self.target_dir = self.job_dir / "target"
        # bulwark_workspace: where bulwark writes all intermediate files + final report
        self.bulwark_workspace = self.target_dir / BULWARK_WORKSPACE_REL
        self.log = log.bind(job_id=env.job_id)

        session = boto3.Session(region_name=env.aws_region)
        self._secrets = session.client("secretsmanager")
        self.dynamo = DynamoWriter(session, env.dynamo_table, env.job_id)
        self.s3 = S3Uploader(session, env.s3_bucket, env.job_id)
        self._parser = BulwarkLogParser(self.dynamo)

    # ── Public entry point ─────────────────────────────────────────────────

    def run(self) -> int:
        try:
            self.dynamo.mark_running()
            api_key = self._fetch_anthropic_key()
        except Exception as exc:
            self.log.error("startup_failed", error=str(exc))
            return EXIT_TERMINAL_INFRA

        try:
            self._prepare_workspace()
        except subprocess.CalledProcessError as exc:
            self.log.error("git_clone_failed", stderr=exc.stderr)
            self.dynamo.mark_failed(reason="UNREACHABLE_REPO", detail=str(exc))
            return EXIT_JOB_UNREACHABLE_REPO
        except Exception as exc:
            self.log.error("workspace_prep_failed", error=str(exc))
            return EXIT_TRANSIENT_INFRA

        self._render_config()

        exit_code = self._run_bulwark(api_key)

        # Always upload whatever artefacts exist, even on partial failure
        try:
            uploaded = self.s3.upload_workspace(self.bulwark_workspace)
            self.s3.upload_report(self.bulwark_workspace)
            self.log.info("artefacts_uploaded", files=uploaded)
        except Exception as exc:
            self.log.error("s3_upload_failed", error=str(exc))
            return EXIT_TRANSIENT_INFRA

        try:
            if exit_code == 0:
                self.dynamo.mark_completed()
            else:
                self.dynamo.mark_failed(
                    reason="BULWARK_ERROR", detail=f"exit_code={exit_code}"
                )
        except Exception as exc:
            self.log.error("dynamo_final_update_failed", error=str(exc))
            return EXIT_TRANSIENT_INFRA

        return exit_code

    # ── Private helpers ────────────────────────────────────────────────────

    def _fetch_anthropic_key(self) -> str:
        resp = self._secrets.get_secret_value(SecretId=self.env.secret_arn_anthropic)
        return str(resp["SecretString"])

    def _prepare_workspace(self) -> None:
        self.job_dir.mkdir(parents=True, exist_ok=True)
        self.log.info("git_clone_start", repo=self.env.target_repo, branch=self.env.target_branch)
        subprocess.run(
            [
                "git", "clone",
                "--depth=1",
                "--branch", self.env.target_branch,
                self.env.target_repo,
                str(self.target_dir),
            ],
            check=True,
            capture_output=True,
            text=True,
        )
        self.log.info("git_clone_done")

    def _render_config(self) -> None:
        scope_items = "\n".join(f'  "{s}",' for s in self.env.target_scope)
        config = textwrap.dedent(f"""\
            # Auto-generated by bulwark-cloud for job {self.env.job_id}
            [target]
            repo   = "{self.env.target_repo}"
            branch = "{self.env.target_branch}"
            scope  = [
            {scope_items}
            ]
            core_contracts = []

            model = "{self.env.model}"
        """)
        (self.job_dir / "bulwark.toml").write_text(config)
        self.log.info("config_rendered", job_dir=str(self.job_dir))

    def _run_bulwark(self, api_key: str) -> int:
        self.log.info("bulwark_start")
        env = {
            **os.environ,
            "ANTHROPIC_API_KEY": api_key,
            # AUDIT_DIR: where bulwark looks for the project source code
            "AUDIT_DIR": str(self.target_dir),
            # BULWARK_ROOT: where bulwark finds bulwark.toml and context/ files
            "BULWARK_ROOT": str(self.job_dir),
            # BULWARK_INSTALL is already set in the Docker image (to /home/auditor)
        }

        proc = subprocess.Popen(
            ["bulwark", "run"],
            env=env,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,   # combine stderr so parser sees all output
            cwd=str(self.job_dir),      # cwd where bulwark.toml is
            text=True,
        )

        assert proc.stdout is not None
        for line in proc.stdout:
            stripped = line.rstrip()
            # Structured progress lines emitted by bulwark to stdout —
            # updates DynamoDB pass records in real time.
            self._parser.handle_line(stripped)
            self.log.info("bulwark_stdout", line=stripped)

        return proc.wait()
